### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Gamer750** [vinaygopinath/launch-chat#20]
Can you suggest me some WhatsApp client for android which are privacy friendly and FOSS

**Comment by barefootstache** [comment]
One could try setting up a WebView for WhatsApp, checking out the [Element One](https://element.io/blog/element-one-all-of-matrix-whatsapp-signal-and-telegram-in-one-place/) approach, or building one's own WhatsApp bridge.

**Comment by Gamer750** [comment]
Bro when you are using  a bridge you are trusting changing the trust from WhatsApp to another man .Bro do you know any good bridge without collecting any meta data

**Comment by vinaygopinath** [comment]
I'm not aware of third-party WhatsApp clients for Android, and this question is out of scope for the issues page. Feel free to continue the conversation in discussions.
