### ISSUE TITLE
Maintain app usage history

### ISSUE THREAD

**Issue by vinaygopinath** [vinaygopinath/launch-chat#23]
# Problem
As a user, I'd like to see the phone numbers, text and contacts I've shared, the phone number and SMS links I've clicked, and the conversations I've launched through Launch Chat

# Solution
Add a new screen to view history

# Requirements
1. Add a new screen accessible from the main screen of the app
2. Add a new component below the "Open with (app)" buttons in the home screen that shows recent entries
3. Show a list of entries in reverse chronological order (most recent entry first)
4. In each entry, show the
    * the time of occurrence
    * the source of data: contact share, link click, text share, manual input
    * the navigation path: did the user open Whatsapp, Signal, or Telegram?
5. When an entry is clicked, trigger the action again (return to the main screen with the input field pre-filled based on the entry)

**Comment by saswatasarkar13** [comment]
Hello, I want to add a point or two.

1.  As the screenshot shows, History can be there and a view more button to go to the full history page. 
![Screenshot_20240628-113256_1](https://github.com/vinaygopinath/launch-chat/assets/63540311/37bf6775-1e98-4fac-9a0c-0824e568bfaa)
2. add the option to re-open like if I have used signal for that number, signal button should be on the right to reopen.

Regards

**Comment by vinaygopinath** [comment]
Thanks for your input @saswatasarkar13, I like the idea! I'll try this out when I get to this issue.
