### ISSUE TITLE
Set up F-Droid release

### ISSUE THREAD

**Issue by vinaygopinath** [vinaygopinath/launch-chat#3]
# Requirements
* Set up a release process
* Document the release process
* Upload release artefact to F-Droid
* Create a Github release

**Comment by vinaygopinath** [comment]
See Gitlab F-Droid PR that adds the "metadata" for the release: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14550

References for submitting to F-Droid and creating the metadata file
* https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md
* https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/
* https://f-droid.org/en/docs/Build_Metadata_Reference/
* Fixing an issue with the use of Gradle 8+: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13999
* Fixing an issue with the use of checkupdate: https://forum.f-droid.org/t/i-cant-get-checkupdate-to-work/24784

**Comment by inson1** [comment]
Also you could then add the screenshots to Readme, I think it would look nice

**Comment by vinaygopinath** [comment]
@licaon-kter @inson1 Done, thank you both!
