### ISSUE TITLE
Separate regular WhatsApp and Business WhatsApp.

### ISSUE THREAD

**Issue by droped** [vinaygopinath/launch-chat#52]
Every time I use LaunchChat with WhatsApp, it opens the business app. Works fine if I don't have the business app installed. No way to change it if I have both installed.

**Comment by vinaygopinath** [comment]
Hi, it sounds like Launch Chat defaults to opening WhatsApp Business as opposed to the personal WhatsApp app.

If you're looking to change that, you can disable WhatsApp Business as the default handler of WhatsApp links (which is what Launch Chat uses) under Settings --> Apps --> WhatsApp Business --> Open by default --> (disable the toggle). You'll need to then go into the Open by default screen for the WhatsApp app and enable the toggle.

![whatsapp-business-open-by-default.png](https://github.com/user-attachments/assets/50ad1bc7-e2c5-4fa1-9a11-6390ea7dd4fa)

Is there an additional ask here? Are you proposing that Launch Chat have separate buttons to "open with WhatsApp" and "open with WhatsApp Business"?

**Comment by vinaygopinath** [comment]
Understood - I'll need to investigate whether WhatsApp Business offers a URL that will specifically open that app, but I'm grouping this under the umbrella of custom messaging systems (See #41), which is planned for the next release. Please follow the other issue for updates/suggestions. Closing this as a duplicate.
