### ISSUE TITLE
Screen protection over "recent apps" and "screenshot"

### ISSUE THREAD

**Issue by serrq** [vinaygopinath/launch-chat#53]
Some apps give the ability (optional) to switch ON/OFF the "screenshot" and "recent apps" protection feature by other prying apps.
Basically a privacy feature. Here an implementation and some examples.

![271815693-2e7d379a-c81c-41b1-88d2-7170fc429af7](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/8177e581-55ce-4aab-b2ed-41fb7fc3c1d8)

![1000042036](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/499a76af-6db7-4f6b-b886-f06ff7dad708)

**Comment by vinaygopinath** [comment]
Hi, thanks for reporting.

I'm aware of the Android feature to prevent screenshots and screencasts, but I'm not sure how that's relevant to Launch Chat.

You mentioned other "prying apps". Is the worry then that other apps would take screenshots/read the content off the Launch Chat screen and scrape phone numbers?

If so, I'm not particularly concerned about an attack vector that requires a malicious app to be installed on a user device - that seems far-fetched to me. On the other hand, disabling screenshots would prevent users from providing visual context when reporting issues, which is a more tangible need (some of the open/closed issues have user-submitted screenshots).

**Comment by vinaygopinath** [comment]
Like I said, the attack vector does not make sense to me. Until an attack vector is proven to exist in the wild, I don't think this is a good use of this project's time and even then it may be a matter of securing the device by not installing malicious apps vs placing the burden of security on all other apps. Closing for now.
